package executor

import (
	"bufio"
	"os"
	"path/filepath"
	"sort"

	"github.com/go-git/go-git/v5"
	"github.com/go-git/go-git/v5/plumbing/format/gitignore"
	"github.com/go-git/go-git/v5/plumbing/object"
)

type CommitResult struct {
	Hash         string
	FilesAdded   int
	FilesUpdated int
	FilesDeleted int
}

func AddAll(path string) error {
	repo, err := OpenRepo(path)
	if err != nil {
		return err
	}
	w, err := repo.Worktree()
	if err != nil {
		return err
	}
	// Replace the .gitignore file with the one in the repo
	replaceGitIgnore(w, filepath.Join(path, ".gitignore"))

	// Add all files
	err = w.AddWithOptions(&git.AddOptions{
		All: true,
	})
	if err != nil {
		return err
	}
	return nil
}

func Commit(path string, message string) (CommitResult, error) {
	repo, err := OpenRepo(path)
	if err != nil {
		return CommitResult{}, err
	}
	w, err := repo.Worktree()
	if err != nil {
		return CommitResult{}, err
	}
	// Replace the .gitignore file with the one in the repo
	replaceGitIgnore(w, filepath.Join(path, ".gitignore"))

	// Add all files
	err = w.AddWithOptions(&git.AddOptions{
		All: true,
	})
	if err != nil {
		return CommitResult{}, err
	}

	status, err := w.Status()
	if err != nil {
		return CommitResult{}, err
	}
	fileAdded := 0
	fileUpdated := 0
	fileDeleted := 0
	for _, v := range status {
		if v.Staging == git.Added {
			fileAdded++
		}
		if v.Staging == git.Deleted {
			fileDeleted++
		}
		if v.Staging == git.Modified {
			fileUpdated++
		}
	}
	hash, err := w.Commit(message, &git.CommitOptions{
		All: true,
	})
	if err != nil {
		return CommitResult{}, err
	}
	return CommitResult{
		Hash:         hash.String(),
		FilesAdded:   fileAdded,
		FilesUpdated: fileUpdated,
		FilesDeleted: fileDeleted,
	}, nil
}

// Load the .gitignore file, and add to the "exclude" section of the worktree
//
// This is a workaround for the fact that go-git does not support .gitignore
func replaceGitIgnore(wk *git.Worktree, path string) {
	f, _ := os.Open(path)
	defer f.Close()

	// Read the file
	scanner := bufio.NewScanner(f)
	scanner.Split(bufio.ScanLines)
	for scanner.Scan() {
		line := scanner.Text()
		// Add the line to the exclude list
		wk.Excludes = append(wk.Excludes, gitignore.ParsePattern(line, nil))
	}

}

/* CODE GENERATED BY COPILOT
 * SHOULD BE TESTED BEFORE USE
 */

// List commit for the current branch
func ListCommit(path string) ([]object.Commit, error) {
	repo, err := OpenRepo(path)
	if err != nil {
		return nil, err
	}
	// Get the branch
	ref, err := repo.Head()
	if err != nil {
		return nil, err
	}
	// Get the commit history
	commitIter, err := repo.Log(&git.LogOptions{From: ref.Hash()})
	if err != nil {
		return nil, err
	}
	// Get the commits
	commits := []object.Commit{}
	err = commitIter.ForEach(func(c *object.Commit) error {
		commits = append(commits, *c)
		return nil
	})
	if err != nil {
		return nil, err
	}
	// Sort the commits by date
	sort.Slice(commits, func(i, j int) bool {
		return commits[i].Author.When.After(commits[j].Author.When)
	})
	return commits, nil
}
